import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import {APP,uid,readJson} from '../src/core.js';
import {Jobs} from '../src/jobs.js';
import {published} from './helpers.js';
import {Media} from '../src/media.js';
test('an uncertain paid response is never resubmitted on resume',async()=>{const dir=path.join(APP,'test-output',uid('media-'));await fs.mkdir(dir,{recursive:true});const file=path.join(dir,'source.mp3');await fs.writeFile(file,'fixture-media');await fs.writeFile(path.join(dir,'audio-0.mp3'),'fixture-chunk');let calls=0;const runner:any=async(_c:string,args:string[])=>({stdout:args.includes('ffprobe')?JSON.stringify({format:{duration:60},streams:[]}):'/fixture',stderr:'',elapsed_ms:1});const request:any=async()=>{calls++;throw Error('Connection dropped after submission');};process.env.KB_TEST_TRANSCRIPTION_TOKEN='synthetic-test-value';try{const m=new Media(runner,request),budget={limit:1,currency:'USD',authorization:'Mock-only accounting test'},config={endpoint:'https://example.invalid/transcribe',model:'fixture',key_env:'KB_TEST_TRANSCRIPTION_TOKEN',estimated_cost_per_minute:.01,currency:'USD'};await assert.rejects(()=>m.convert(file,dir,budget,config),/Connection dropped/);assert.equal((await readJson(path.join(dir,'transcription-requests.json')))[0].status,'uncertain');await assert.rejects(()=>m.convert(file,dir,budget,config),{code:'PROVIDER_OUTCOME_UNCERTAIN'});assert.equal(calls,1);}finally{delete process.env.KB_TEST_TRANSCRIPTION_TOKEN;}});
test('media conversion cannot submit without an explicit budget',async()=>{let calls=0;const m=new Media(undefined,async()=>{calls++;throw Error('Unexpected submission');});await assert.rejects(()=>m.convert('unused','unused',undefined as any,{}),{code:'PAID_BUDGET_REQUIRED'});assert.equal(calls,0);});

test('multiple media sources share one durable job reservation limit',async()=>{const f=await published(),jobs=new Jobs(f.store),source=f.store.p('budget-source.txt');await fs.writeFile(source,'Budget fixture');const j=await jobs.ingest({paths:[source],module:f.scope.write_modules[0],domains:['lumen'],idempotency_key:'budget',authorization:'Mock budget test'}),budget={limit:1,currency:'USD',authorization:'Allow one dollar for the whole fixture job'};await jobs.reservePaid(j.job.job_id,'first-file',.6,budget);await jobs.reservePaid(j.job.job_id,'first-file',.6,budget);await assert.rejects(()=>jobs.reservePaid(j.job.job_id,'second-file',.6,budget),{code:'PAID_BUDGET_REQUIRED'});const a=await readJson(path.join(jobs.jobPath(j.job.job_id),'paid-accounting.json'));assert.equal(a.estimated_reserved,.6);assert.equal(a.reservations.length,1);});
