import * as fs from 'node:fs/promises';
import path from 'node:path';
import { Store } from './store.js';
import { Projections } from './projections.js';
import { ensure, readJson, immutable, atomic, safePath, exists, hash, json, now, uid, key, ref, recordRefs } from './core.js';
import type { Ref,RecordData } from './core.js';
async function walk(root:string,prefix=''):Promise<string[]>{const results:string[]=[];for(const e of await fs.readdir(path.join(root,prefix),{withFileTypes:true})){ensure(!e.isSymbolicLink(),'VALIDATION_FAILED','Export cannot follow symlinks');const p=prefix?prefix+'/'+e.name:e.name;if(e.isDirectory())results.push(...await walk(root,p));else results.push(p);}return results;}
export class Maintenance {
  constructor(public store:Store,public projections=new Projections(store)){}
  async verify(){const records=await this.store.records(),errors:string[]=[];for(const r of records.values()){try{await this.store.read(ref(r));if(r.record_type==='source'){const p=r.payload as any;ensure(hash(await fs.readFile(await safePath(this.store.root,p.original_path)))===p.sha256,'VALIDATION_FAILED','Original hash mismatch');}if(r.record_type==='passage')await this.store.verifyLocator(r,await this.store.exact((r.payload as any).source_ref));}catch(e:any){errors.push({id:r.id,error:e.message} as any);}}return {records:records.size,valid:errors.length===0,errors,views:await this.projections.verifyViews().catch(e=>({valid:false,error:e.message}))};}
  async exportBundle(){const release=await this.store.release();ensure(release,'VALIDATION_FAILED','No release to export');const ledger=await this.store.ledger(),name=uid('bundle-'),target=this.store.p('exports/'+name);await fs.mkdir(target,{recursive:true});const files:Record<string,string>={};
    for(const f of await walk(this.store.root)){if(/^(exports|views)\//.test(f)||f.startsWith('.')||f==='CURRENT'||f==='publication.json')continue;if(f.startsWith('objects/')&&ledger.blocked_ids.some(id=>f.startsWith('objects/'+id.replace(':','_')+'/')))continue;const bytes=await fs.readFile(this.store.p(f));await immutable(path.join(target,f),bytes);files[f]=hash(bytes);}
    await immutable(path.join(target,'CURRENT'),release.release_id+'\n');files.CURRENT=hash(release.release_id+'\n');const bundle={version:1,corpus_id:release.corpus_id,release_id:release.release_id,created_at:now(),ledger_generation:ledger.generation,record_ids:[...(await this.store.records()).keys()],files,media:'full',credentials_included:false};await immutable(path.join(target,'bundle.json'),json(bundle));await this.store.audit('export','Created a portable full backup',[],release.release_id);return {path:target,manifest:bundle};
  }
  async restoreBundle(bundlePath:string,target:string){const bundle=await readJson(path.join(bundlePath,'bundle.json'));ensure(!await exists(path.join(target,'corpus.json')),'REVISION_CONFLICT','Restore destination already contains a corpus');const ledger=await readJson(path.join(this.store.ledgerRoot,hash(bundle.corpus_id)+'.json')).catch(()=>null);ensure(ledger,'LEDGER_UNAVAILABLE','Restore requires the independently retained deletion ledger');ensure(bundle.ledger_generation===ledger.generation,'LEDGER_UNAVAILABLE','Backup predates deletion policy; restore must be reconciled before use');
    const staging=target+'.restore-'+uid();await fs.mkdir(staging,{recursive:true});for(const [relative,digest] of Object.entries(bundle.files)){const bytes=await fs.readFile(await safePath(bundlePath,relative));ensure(hash(bytes)===digest,'VALIDATION_FAILED','Backup checksum mismatch',{relative});await immutable(await safePath(staging,relative,true),bytes);}const restored=new Store(staging,this.store.project,this.store.ledgerRoot);await restored.records();await fs.rename(staging,target);return {path:target,release_id:bundle.release_id,indexes:'Rebuild with kb_maintain reindex'};
  }
  async wikiEdit(record:Ref){const r=await this.store.exact(record),release=await this.store.current();ensure(release,'VALIDATION_FAILED','No release');const wiki=this.store.p(`views/${release}/wiki/${hash(r.id).slice(0,24)}.md`),content=await fs.readFile(wiki,'utf8');return {record_ref:record,generated_file:wiki,proposed_markdown:content.replace(/^---[\s\S]*?---\s*/,'').split('\n## Provenance\n')[0],instruction:'Review meaning and cite changes, then submit kb_propose with existing_ref. This has not changed canonical prose.'};}
  async previewBulk(proposal:any){const plan={plan_id:uid('bulk-'),base_release:await this.store.current(),proposal,hash:hash(json(proposal)),created_at:now()};await immutable(this.store.p(`lifecycle/bulk/${plan.plan_id}.json`),json(plan));return plan;}
  async exportFormats(){const release=await this.store.release();ensure(release,'VALIDATION_FAILED','No release');const records=await this.store.records();const rows=['id,revision,title,sources,epistemic'];for(const r of records.values())rows.push([r.id,r.revision,r.title,r.provenance.source_refs.map(key).join(';'),r.epistemic].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','));const dir=this.store.p(`views/${release.release_id}/exports`);await fs.mkdir(dir,{recursive:true});await atomic(path.join(dir,'citations.csv'),rows.join('\n'));await atomic(path.join(dir,'records.jsonl'),[...records.values()].map(r=>JSON.stringify(r)).join('\n'));const diagram=['flowchart TD'];for(const r of records.values())if(r.record_type==='relationship'){const p=r.payload as any;diagram.push(`  n${hash(p.subject.id).slice(0,10)}["${p.subject.id}"] -->|${p.predicate}| n${hash(p.object.id).slice(0,10)}["${p.object.id}"]`);}await atomic(path.join(dir,'relationships.mmd'),diagram.join('\n'));return {path:dir};}
  async importBundle(bundlePath:string,module:string,domains:string[]){const bundle=await readJson(path.join(bundlePath,'bundle.json'));const config=await this.store.config();ensure(bundle.corpus_id!==config.corpus_id,'REVISION_CONFLICT','Use restore for the same corpus');const scope=await this.store.scope();ensure(scope.write_modules.includes(module),'SCOPE_DENIED','Import module is not writable');const current=await this.store.current(),release=await readJson(path.join(bundlePath,`releases/${bundle.release_id}.json`));const mapping=new Map<string,Ref>(),records:RecordData[]=[],bodies:Record<string,string>={};
    const currentRefs=new Set<string>(release.records.map((e:any)=>key(e.record_ref))),entries=new Map<string,any>();for(const f of Object.keys(bundle.files))if(/^releases\/release-[a-z0-9-]+\.json$/.test(f)){const bytes=await fs.readFile(await safePath(bundlePath,f));ensure(hash(bytes)===bundle.files[f],'VALIDATION_FAILED','Imported release checksum mismatch');const historical=JSON.parse(bytes.toString());for(const entry of historical.records)if(bundle.files[entry.metadata_path])entries.set(key(entry.record_ref),entry);}
    for(const entry of entries.values()){const bytes=await fs.readFile(await safePath(bundlePath,entry.metadata_path));ensure(hash(bytes)===entry.sha256&&bundle.files[entry.metadata_path]===entry.sha256,'VALIDATION_FAILED','Imported record checksum mismatch');const old=JSON.parse(bytes.toString()) as RecordData;mapping.set(key(old),{id:old.record_type+':'+hash(bundle.corpus_id+':'+key(old)).slice(0,28),revision:1});records.push(old);}
    const folders=new Map<string,string>();for(const old of records)if(old.record_type==='source')folders.set(path.posix.dirname((old.payload as any).original_path),`sources/import-${hash(bundle.corpus_id+old.id).slice(0,24)}/1`);
    const remapPaths=(v:any):any=>{if(typeof v==='string'){for(const [from,to] of folders)if(v.startsWith(from+'/'))return to+v.slice(from.length);return v;}if(Array.isArray(v))return v.map(remapPaths);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,remapPaths(x)]));return v;};
    const expand=(v:any):any=>{if(Array.isArray(v))return v.map(expand);if(v&&typeof v==='object'){if(Object.keys(v).length===2&&v.id&&v.revision){ensure(mapping.has(key(v)),'VALIDATION_FAILED','Imported historical reference needs an explicit revision mapping');return mapping.get(key(v));}return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,expand(x)]));}return v;};
    for(let i=0;i<records.length;i++){const old=records[i],r=expand(old) as RecordData;Object.assign(r,mapping.get(key(old)));r.corpus_id=config.corpus_id;r.maintenance_module=module;r.scope.domains=domains;r.provenance.method=`import:${bundle.corpus_id}:${key(old)}`;if(!currentRefs.has(key(old)))r.archived=true;
      if(old.body){const bytes=await fs.readFile(await safePath(bundlePath,old.body.path));ensure(hash(bytes)===old.body.sha256,'VALIDATION_FAILED','Imported prose hash mismatch');r.body={path:`objects/${r.id.replace(':','_')}/1/body.md`,sha256:hash(bytes)};bodies[key(r)]=bytes.toString();}
      if(r.record_type==='source'){const p=r.payload as any,oldPath=p.original_path,folder=path.posix.dirname(oldPath),newFolder=folders.get(folder)!;for(const [f,digest] of Object.entries(bundle.files))if(f.startsWith(folder+'/')){let bytes=await fs.readFile(await safePath(bundlePath,f));ensure(hash(bytes)===digest,'VALIDATION_FAILED','Imported source checksum mismatch');if(f.endsWith('/extraction.json'))bytes=Buffer.from(json(remapPaths(JSON.parse(bytes.toString()))));await immutable(this.store.p(newFolder+f.slice(folder.length)),bytes);}p.original_path=newFolder+'/'+path.posix.basename(oldPath);}
      if(r.record_type==='passage'&&(r.payload as any).asset_path)(r.payload as any).asset_path=remapPaths((r.payload as any).asset_path);
      records[i]=r;
    }
    const result=await this.store.publish(records,bodies,current,'Imported explicitly selected portable research bundle; original revisions retained as separate archived identities with origin mapping',scope);await immutable(this.store.p(`imports/${hash(bundle.corpus_id+bundle.release_id)}.json`),json({source_corpus:bundle.corpus_id,source_release:bundle.release_id,mapping:Object.fromEntries(mapping),semantics:'Each original revision has an exact new identity; historical revisions are archived, not collapsed into the latest version.',release_id:result.release_id}));return result;
  }
}
